name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches: [dev]

  pull_request:
    branches: [dev]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build Next.js app
        run: yarn build
